# Site settings
baseurl = "https://www.mariusurbelis.com/art"
languageCode = "en-us"
title = "Photo Grid - Grid Gallery For Hugo"
theme = "photo-grid"

[params]
    # Meta
    no_exif = false
    title = "Marius Urbelis"
    author = "Marius Urbelis"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    copyright_since_year = 2017
    copyright_text = "All images"